# Generated by Django 5.0.4 on 2024-04-11 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecard',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='coursecard',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursecard',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursecard',
            name='playlist_resource',
            field=models.CharField(default='url', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecard',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='level',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
